import Head from "next/head";
import Image from "next/image";
import { motion } from "framer-motion";

export default function Home() {
  return (
    <div className='overflow-hidden bg-[#1A1A1A] w-full h-screen relative flex flex-col items-center justify-around py-[100px] text-blood '>
      <Head>
        <title>HAUNTED HOOLIGANS</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/Banner.svg' />
      </Head>

      {/* hand 1 */}
      <motion.img
        initial={{ x:-200 }}
        animate={{ x: 0 }}
        transition={{ duration: 2 , ease: "easeOut" }}
        src='/left.svg'
        alt='right hand'
        className='absolute w-[500px] left-0 hidden lg:flex '
      />
      <motion.img
      initial={{ x:200 }}
      animate={{ x: 0 }}
      transition={{ duration: 2 , ease: "easeOut" }}
        src='/right.svg'
        alt='right hand'
        className='absolute w-[500px] right-0 hidden lg:flex '
      />
      <div className='absolute left-[30px] top-[30px] lg:left-[60px] cursor-pointer '>
        <Image
          style={"color: #EA3F3E;"}
          src='/twitter.svg'
          alt='Twitter icon'
          width='40px'
          height='40px'
        />
      </div>

      {/* icon head */}
      <div className='animate-bounce flex items-center justify-center border-2 border-blood w-[200px] h-[200px] lg:w-[300px] lg:h-[300px]  rounded-full'>
        <Image src='/Logo.svg' width='300%' height='250%' />
      </div>

      <h1 className='text-[40px] lg:text-[60px] text-center'>
        HAUNTED HOOLIGANS
      </h1>

      <h2 className='text-center text-[25px] lg:text-[35px]'>
        GET YOUR HANDS ON OUR EXCLUSIVE HALLOWEEN EDITION
      </h2>
      <button className='animate-pulse text-[20px] lg:text-[30px]  border-dashed border-2 border-blood p-[10px] flex items-center '>
        MINT SOON
      </button>
    </div>
  );
}
